/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VersionResponse {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "stable", skip_serializing_if = "Option::is_none")]
    pub stable: Option<bool>,
}

impl VersionResponse {
    pub fn new() -> VersionResponse {
        VersionResponse {
            version: None,
            stable: None,
        }
    }
}


