//
// VersionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VersionResponse: Codable, Hashable {

    public var version: String?
    public var stable: Bool?

    public init(version: String? = nil, stable: Bool? = nil) {
        self.version = version
        self.stable = stable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case stable
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(stable, forKey: .stable)
    }
}

