//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelErrorResponse: Codable, Hashable {

    public var message: String
    public var code: String
    public var error: String?

    public init(message: String, code: String, error: String? = nil) {
        self.message = message
        self.code = code
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case code
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

