/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.domain.projectname.api;

import com.domain.projectname.client.ApiException;
import com.domain.projectname.models.VersionDto;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for ApiInfoApi
 */
@Ignore
public class ApiInfoApiTest {

	private final ApiInfoApi api = new ApiInfoApi();


	/**
	 * Get API version
	 * <p>
	 * Get API version
	 *
	 * @throws ApiException if the Api call fails
	 */
	@Test
	public void getVersionTest() throws ApiException {
		VersionDto response = api.getVersion();
		// TODO: test validations
	}

}
