/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.domain.projectname.api;

import com.domain.projectname.client.ApiException;
import com.domain.projectname.models.ErrorResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GreetingControllerImplApi
 */
@Ignore
public class GreetingControllerImplApiTest {

    private final GreetingControllerImplApi api = new GreetingControllerImplApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void greetHumanTest() throws ApiException {
        String name = null;
                String response = api.greetHuman(name);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void greetWorldTest() throws ApiException {
                String response = api.greetWorld();
        // TODO: test validations
    }
    
}
