"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ProjectName.Client
from ProjectName.Client.api.greeting_controller_impl_api import GreetingControllerImplApi  # noqa: E501


class TestGreetingControllerImplApi(unittest.TestCase):
    """GreetingControllerImplApi unit test stubs"""

    def setUp(self):
        self.api = GreetingControllerImplApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_greet_human(self):
        """Test case for greet_human

        """
        pass

    def test_greet_world(self):
        """Test case for greet_world

        """
        pass


if __name__ == '__main__':
    unittest.main()
