/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing GreetingControllerImplApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GreetingControllerImplApiTests : IDisposable
    {
        private GreetingControllerImplApi instance;

        public GreetingControllerImplApiTests()
        {
            instance = new GreetingControllerImplApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GreetingControllerImplApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GreetingControllerImplApi
            //Assert.IsType<GreetingControllerImplApi>(instance);
        }

        /// <summary>
        /// Test GreetHuman
        /// </summary>
        [Fact]
        public void GreetHumanTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //var response = instance.GreetHuman(name);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test GreetWorld
        /// </summary>
        [Fact]
        public void GreetWorldTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GreetWorld();
            //Assert.IsType<string>(response);
        }
    }
}
