description: "Executes a gradle task with the gradle wrapper"
name: update message
inputs:
  task:
    description: "The gradle task"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: verify gradle-wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Global gradle cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: local gradle cache
      uses: actions/cache@v2
      with:
        path: |
          .gradle/
          modules/*/build/
        key: ${{ runner.os }}-gradle-build-${{ github.ref }}
    - name: prepare gradle
      run: chmod +x gradlew
      shell: bash
    - name: execute task
      run: ./gradlew ${{ inputs.task }} --build-cache --parallel
      shell: bash
    - name: stop gradle deamon
      run: ./gradlew --stop
      shell: bash

