/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ProjectName.Client.Client;
using ProjectName.Client.Api;
// uncomment below to import models
//using ProjectName.Client.Model;

namespace ProjectName.Client.Test.Api
{
    /// <summary>
    ///  Class for testing ApiControllerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ApiControllerApiTests : IDisposable
    {
        private ApiControllerApi instance;

        public ApiControllerApiTests()
        {
            instance = new ApiControllerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiControllerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ApiControllerApi
            //Assert.IsType<ApiControllerApi>(instance);
        }

        /// <summary>
        /// Test Version
        /// </summary>
        [Fact]
        public void VersionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Version();
            //Assert.IsType<VersionResponse>(response);
        }
    }
}
