/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.util.Set;
import org.openapitools.client.model.TodoEntryDto;
import org.openapitools.client.model.TodoListDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TodoControllerImplApi
 */
@Ignore
public class TodoControllerImplApiTest {

    private final TodoControllerImplApi api = new TodoControllerImplApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createItemTest() throws ApiException {
        String name = null;
        TodoEntryDto todoEntryDto = null;
                api.createItem(name, todoEntryDto);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * Add a new todo list
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createListTest() throws ApiException {
        TodoListDto todoListDto = null;
                api.createList(todoListDto);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteItemTest() throws ApiException {
        String name = null;
        String itemName = null;
                api.deleteItem(name, itemName);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteListTest() throws ApiException {
        String name = null;
                api.deleteList(name);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getItemTest() throws ApiException {
        String name = null;
        String itemName = null;
                TodoEntryDto response = api.getItem(name, itemName);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getItemNamesTest() throws ApiException {
        String name = null;
                Set<String> response = api.getItemNames(name);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getItemsTest() throws ApiException {
        String name = null;
                Set<TodoEntryDto> response = api.getItems(name);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get a list of todo items with the specified name
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        String name = null;
                TodoListDto response = api.getList(name);
        // TODO: test validations
    }
    
    /**
     * Get all lists
     *
     * Get a list of all todo lists
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getListsTest() throws ApiException {
                Set<TodoListDto> response = api.getLists();
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setDoneTest() throws ApiException {
        String list = null;
        String itemName = null;
        Boolean done = null;
                api.setDone(list, itemName, done);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateItemTest() throws ApiException {
        String name = null;
        String itemName = null;
        TodoEntryDto todoEntryDto = null;
                api.updateItem(name, itemName, todoEntryDto);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateListTest() throws ApiException {
        String name = null;
        TodoListDto todoListDto = null;
                api.updateList(name, todoListDto);
        // TODO: test validations
    }
    
}
