// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    ErrorResponse,
    VersionResponse,
} from '../models';

/**
 * no description
 */
export class ApiControllerApi extends BaseAPI {

    /**
     */
    version(): Observable<VersionResponse>
    version(opts?: OperationOpts): Observable<RawAjaxResponse<VersionResponse>>
    version(opts?: OperationOpts): Observable<VersionResponse | RawAjaxResponse<VersionResponse>> {
        return this.request<VersionResponse>({
            url: '/api/version',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
