<?php
/**
 * GreetingControllerImplApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  com.domain.projectname.client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace com.domain.projectname.client\Test\Api;

use \com.domain.projectname.client\Configuration;
use \com.domain.projectname.client\ApiException;
use \com.domain.projectname.client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GreetingControllerImplApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.domain.projectname.client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GreetingControllerImplApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for greetHuman
     *
     * .
     *
     */
    public function testGreetHuman()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for greetWorld
     *
     * .
     *
     */
    public function testGreetWorld()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
