name: Build

on:
  pull_request:
    branches:
      - master
      - dev
      - main
      - staging
      - hotfix
    types: [ synchronize, opened ]
  push:
    branches:
      - master
      - dev
      - main
      - staging
      - hotfix

jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: gradle check
        uses: ./.github/actions/gradle
        env:
          #This will cause issues as it will not be available on a fork branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          task: check sonarqube
  openapi_diff:
    runs-on: ubuntu-latest
    name: OpenAPI
    needs: testing
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Check api changes
        uses: tony84727/changed-file-filter@v0.2.0
        id: filter
        with:
          filters: |
            api:
              - 'modules/api/src/**/*.*'
      - name: Build PR OAS
        if: steps.filter.outputs.api == 'true'
        uses: ./.github/actions/gradle
        with:
          task: generateOpenApiDocs
      - name: Checkout base branch
        if: steps.filter.outputs.api == 'true'
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.base_ref }}
          path: 'base'
      - name: Build OAS diff
        if: steps.filter.outputs.api == 'true'
        uses: nbrugger-tgm/open-api-diff-notes-action@master
        with:
          headFile: openapi.json
          baseFile: base/openapi.json
          output_path: ~/openapi_diff.json
          github_token: ${{ secrets.GITHUB_TOKEN }}