name: Create release
on:
  workflow_dispatch:

jobs:
  create_rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: staging
          destination_branch: main              # If blank, default: master
          pr_title: "Create Release Candidate"
          pr_body: "This is a release candidate for the next version of the project."              # Full markdown support, requires pr_title to be set
          github_token: ${{ secrets.PAT }}