name: Create pre-release
on:
  workflow_dispatch:

jobs:
  create_rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: staging
          branch: dev
          title: "Create Release Candidate"
          body: "This is a release candidate for the next version of the project."