semver:
  name: Create release
  runs-on: ubuntu-latest
  needs: prebuild
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Scan release stage
      id: branch
      run: |
        if [ "${{ github.base_ref }}" == 'main']; then
          echo "::set-output name=release_stage::release"
        elif [ "${{ github.base_ref }}" == 'staging' ]; then
          echo "::set-output name=release_stage::rc"
        elif [ "${{ github.base_ref }}" == 'dev' || "${{ github.base_ref }}" == 'hotfix' ]; then
          echo "::set-output name=release_stage::beta"
        fi
    - id: cz_pr
      name: Bump prerelase-version
      if: steps.branch.outputs.release_stage != 'release'
      uses: commitizen-tools/commitizen-action@0.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        changelog_increment_filename: changelog_diff.md
        prerelease: ${{ steps.branch.outputs.release_stage }}
    - id: cz
      name: Bump release-version
      if: steps.branch.outputs.release_stage == 'release'
      uses: commitizen-tools/commitizen-action@0.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        changelog_increment_filename: changelog_diff.md
    - name: download build
      uses: actions/download-artifact@v2
      with:
        name: base-build
    - name: Build Artifact
      run: |
        chmod +x gradlew
        ./gradlew bootJar
    - uses: ncipollo/release-action@v1.8.10
      id: release
      with:
        artifacts: app/build/lib/app-${{ env.REVISION }}.jar
        bodyFile: "changelog_diff.md"
        draft: true
        prerelease: ${{ steps.branch.outputs.release_stage != 'release' }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.REVISION }}
    - name: Add release message
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          ### Release
          This PR will be included in `${{ env.REVISION }}`. [**GH Release**](${{steps.release.outputs.html_url}})
